db:
 image: docker.io/mysql
 ports:
  - "3306:3306"
 environment:
  - MYSQL_ROOT_PASSWORD=admin
 command:
  - --character-set-server=utf8mb4
  - --collation-server=utf8mb4_unicode_ci
 volumes:
  - ~/Desktop/work/dev/volumns/springMysqldb:/var/lib/mysql